version: '3'
services:

  nginx:
    image: nginx:alpine
    container_name: imctech-nginx
    restart: unless-stopped
    ports:
      - ${URL_PORT}:80
    volumes:
      - ${APP_PATH}:/var/www/html/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    image: imctech
    container_name: imctech-php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ${APP_PATH}:/var/www/html/

  node:
    image: node:19
    container_name: imctech-node
    working_dir: /var/www/html
    volumes:
      - ${APP_PATH}:/var/www/html/