version: '3'

services:

  nginx:
    image: nginx
    ports:
      - ${URL_PORT}:80
    volumes:
      - ${APP_PATH}:/var/www/html/
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    environment:
      - NGINX_RUN_USER=#1000
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80\

  php:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ${APP_PATH}:/var/www/html/

  composer:
    image: composer:2
    volumes:
      - ${APP_PATH}:/var/www/html/
    working_dir: /var/www/html/
    command: composer install